name: Run AI Bot Daily

on:
  schedule:
    - cron: "15 3 * * 1-5" # 9:15 AM IST
  workflow_dispatch:

jobs:
  run-ai:
    runs-on: ubuntu-latest
    timeout-minutes: 375

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_enhanced.txt

      - name: Run AI Bot and Save Logs
        run: |
          mkdir -p logs
          touch logs/output.log
          echo "Starting scheduled bot run at $(date)" | tee -a logs/output.log

          end_time=$(date -u -d "today 10:00 UTC" +%s)
          while [ $(date +%s) -lt $end_time ]; do
            echo "Launching bot at $(date)" | tee -a logs/output.log
            python start_enhanced_bot.py --auto 2>&1 | tee -a logs/output.log || \
              echo "Bot crashed with exit code $? at $(date)" | tee -a logs/output.log
            echo "Bot exited, restarting in 30s..." | tee -a logs/output.log
            sleep 30
          done

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs
          path: logs/output.log
