name: Run Indian Bot on Schedule

on:
  # Schedule the bot to run every day at 9:15 AM IST (which is 3:45 UTC)
  # Format: minute hour day(month) month day(week)
  # To run only on weekdays (Mon-Fri), use: '45 3 * * 1-5'
  schedule:
    - cron: '45 3 * * *'

  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # The bot will run for 6h 15m (9:15 AM to 3:30 PM IST)
    # 6 hours * 60 mins/hr + 15 mins = 375 minutes
    timeout-minutes: 375

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.12.3  # <-- UPDATED VERSION
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' # <-- UPDATED VERSION
          cache: 'pip' # cache dependencies to speed up subsequent runs

      - name: 3. Install Dependencies
        # <-- UPDATED FILENAME
        run: pip install -r requirements_enhanced.txt

      - name: 4. Run the Bot and Capture Logs
        # This command runs your bot and saves all console output (both stdout and stderr)
        # into a file named 'bot.log'.
        # IMPORTANT: If you need API keys, remember to add the 'env:' block here
        # with your GitHub Secrets.
        run: python start_enhanced_bot.py --auto > bot.log 2>&1

      - name: 5. Upload Logs on Completion/Timeout
        # This step will ALWAYS run, even if the previous step is terminated by the timeout.
        # This is crucial for getting the logs from the run.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs-${{ github.run_id }}
          path: bot.log
